file:
  workingDir: "![444U4xUqoBCHmJHYYVh+f7bejzNRua0RAz3GZXY8yNAc0Q9jn70PPPfK5ZXLRUeH]"
  input: "InputFiles/"
  error: "Error/ErrorFile"
  write: ""
  
database:
  host: "![LbCQrRqKUqtzuRUIn5Kasw==]"
  port: "![bMV4zaAdJkI=]"
  db: "![+gLltMYL8zQ=]"
  user: "![UIdNErs2ZK8=]"